iQEcBAABAgAGBQJPNksZAAoJEFwvZWOfSHyzBZQH/R8nyqYsVXTA6wyKzZo1J13/  hOjQ73vqWXwrrNOPtrJwxvyO4JxhYU+BVI96uVtmEyE1KkDhzTBy9cIZ+WeItwTb  WRQpo83/tAHH7l8T3xpGgz+u2Fcdwq+7rk297Ps/g4YUVj1lyjcfpDt98N1TN+Ky  aqYUvFtlAkdVjJV2yjKwtm2ZeTCcmYWDOWXYJuymDj1m/ivToAVZhhQGpCQoQBAd  tPbY7LGRbRCQOoHIoynH1yrkMSCndJFS5ztotK9nwG3a6DSXEmPHw39myuKbgyqC  sWkL/+b5FQN0YxHbSfQyOIiOQugzJizWswBQsfzVQC0b0alaQ2itDCVOZyxe3wo=  =hXUp  -----END PGP SIGNATURE-----
ppc: remove unused variables

Fix this error:
/src/qemu/target-ppc/helper.c: In function 'booke206_tlb_to_page_size':
/src/qemu/target-ppc/helper.c:1296:14: error: variable 'tlbncfg' set but not used [-Werror=unused-but-set-variable]

Tested-by: Andreas Färber <afaerber@suse.de>
Signed-off-by: Blue Swirl <blauwirbel@gmail.com>